// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKPZId3AAwPwg82YLA3JvCZaTmyRmAyro',
    appId: '1:581552304160:web:95781668977a47b7ae8c45',
    messagingSenderId: '581552304160',
    projectId: 'gaming-blog-7730f',
    authDomain: 'gaming-blog-7730f.firebaseapp.com',
    storageBucket: 'gaming-blog-7730f.firebasestorage.app',
    measurementId: 'G-DCN7BTNSWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX0GuYUb4eXceexoF9tY1Y-i_1afRxBxg',
    appId: '1:581552304160:android:5eb4a8fbc1b9c125ae8c45',
    messagingSenderId: '581552304160',
    projectId: 'gaming-blog-7730f',
    storageBucket: 'gaming-blog-7730f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDStdSvmmAPRVVeVPFfZAromxODe6-prS4',
    appId: '1:581552304160:ios:f46b65ac3099650bae8c45',
    messagingSenderId: '581552304160',
    projectId: 'gaming-blog-7730f',
    storageBucket: 'gaming-blog-7730f.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDStdSvmmAPRVVeVPFfZAromxODe6-prS4',
    appId: '1:581552304160:ios:f46b65ac3099650bae8c45',
    messagingSenderId: '581552304160',
    projectId: 'gaming-blog-7730f',
    storageBucket: 'gaming-blog-7730f.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKPZId3AAwPwg82YLA3JvCZaTmyRmAyro',
    appId: '1:581552304160:web:923e10f9fe4d9310ae8c45',
    messagingSenderId: '581552304160',
    projectId: 'gaming-blog-7730f',
    authDomain: 'gaming-blog-7730f.firebaseapp.com',
    storageBucket: 'gaming-blog-7730f.firebasestorage.app',
    measurementId: 'G-XDFYND4YB2',
  );
}
